### ISSUE TITLE
Release a v0.1.0

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/splits-io-api#3]
We soon want to release a version on crates.io, so it can be used from other crates such as livesplit-core.

This is blocked on our dependencies releasing non-preview crates now:
- [ ] hyper-rustls - There is a PR https://github.com/ctz/hyper-rustls/pull/96
    - [x] tokio-rustls - Released as 0.12.0
    - [x] hyper - Released as 0.13.0, PR is merged https://github.com/hyperium/hyper/pull/2030
        - [x] h2 - Released as 0.2.0, PR is merged https://github.com/hyperium/h2/pull/428
            - [x] http - Released as 0.2.0 https://github.com/hyperium/http/releases/tag/v0.2.0

Alternatively
- [x] hyper-tls - Released as 0.4.0, PR is merged https://github.com/hyperium/hyper-tls/pull/54

**Comment by CryZe** [comment]
Done :) https://crates.io/crates/splits-io-api

**Comment by martell** [comment]
Congrats @CryZe 🎉
